### ISSUE TITLE
https://www.swimos.org/tutorials is a broken link

### ISSUE THREAD

**Issue by cer** [swimos/swim#122]
```
404 Not Found
Code: NoSuchKey
Message: The specified key does not exist.
Key: www.swimos.org/www.swimos.org/tutorials/index.html
RequestId: T1NPKJ2N3ZN38Y9A
HostId: 3j/pvI2NOeFkyLcY0iezIWsbAIT3P1ryqvhlPiR7vbk9W6XCIii+i4KeVEYxm+0WeZUTHTeIEjo=
An Error Occurred While Attempting to Retrieve a Custom Error Document
Code: NoSuchKey
Message: The specified key does not exist.
Key: error.html

```

**Comment by afolson** [comment]
@cer Thanks for the report! Which page redirected you to www.swimos.org/www.swimos.org/tutorials/index.html ?

**Comment by ajay-gov** [comment]
[https://www.swimos.org/tutorials ](https://www.swimos.org/tutorials) leads to a 404 error. Note that lack of a trailing  "/"

[https://www.swimos.org/tutorials/ ](https://www.swimos.org/tutorials/) works.

**Comment by afolson** [comment]
Closed in this PR: https://github.com/swimos/swimos-docs/pull/113
