### ISSUE TITLE
The @fabric definition does not specify TransitPlane

### ISSUE THREAD

**Issue by cer** [swimos/swim#124]
https://www.swimos.org/tutorials/transit.html says:

> Then, within the @fabric definition, we specify the Java class that will serve as our application entry point, TransitPlane.

Yet TransitPlane does not appear in 

<img width="757" alt="image" src="https://github.com/swimos/swim/assets/246234/0f0943be-f86c-49c3-8b8e-69ff848118b5">

**Comment by ajay-gov** [comment]
@StreamingDataApps is this fixed? Can we close?

**Comment by ajay-gov** [comment]
Fixed with [PR 80](https://github.com/swimos/swimos-docs/pull/80)
