### ISSUE TITLE
swim.concurrent.SyncSpec await timeout ends too soon

### ISSUE THREAD

**Issue by SirCipher** [swimos/swim#24]
The test `awaitTimeout` is occasionally ending too soon. 

```
swim.concurrent.SyncSpec > awaitTimeout FAILED
    java.lang.AssertionError: long too soon: dt: 402276200 expected [true] but found [false]
        at org.testng.Assert.fail(Assert.java:96)
        at org.testng.Assert.failNotEquals(Assert.java:776)
        at org.testng.Assert.assertTrue(Assert.java:44)
        at swim.concurrent.SyncSpec.awaitTimeout(SyncSpec.java:62)
```

This was [moved over](https://github.com/swimos/swim-system-java/commit/f8787d86bd3ae7cfc07f8a77a4009ffefd4cc95b) to using `System.nanoTime()` like the underlying `await` method is using. This did appear to reduce the frequency of this failure, however, it is still present.

Reference failure: https://dev.azure.com/SwimAi/swim-system-java/_build/results?buildId=58 jdk8_windows_s2012#720.

**Comment by horned-sphere** [comment]
From that failure trace, it looks like the test failed becaused the agent was just going very slowly (and so it took more than 200ms to get to the check). Maybe the grace period should just be increased to 3*timeout?

**Comment by SirCipher** [comment]
Resolved in https://github.com/swimos/swim-system-java/commit/b53acba276cffd31707e2b9ed86607cf1d635264
