### ISSUE TITLE
Inconsistent results of checkstyle

### ISSUE THREAD

**Issue by DobromirM** [swimos/swim#3]
The `checkstyleMain` and `checkstyleTest` Gradle tasks display warnings only the first time that they are executed. 

**Steps for reproducing the behaviour:**
1) Open a file and change the order of import statements so that the they violate the style.
2) Run either `checkstyleMain` or `checkstyleTest` depending on whether you changed a source file or a test file. At this step, Gradle will report a warning when the task is running.
3) Without changing anything, run the task again. Gradle will not report any warnings.

**Explanation:**
This happens due to the fact that on step two, the style problems are reported as warnings and Gradle mark the tasks as successful (Gradle tasks fail only on errors and not on warnings). When the same task is executed again without any changes to the files, Gradle uses it's cache to display that it is successful instead of actually running the check.

**Possible solutions:**

1) Force Gradle to never use the cache for `checkstyleMain` or `checkstyleTest`. This can be done by adding `outputs.upToDateWhen { false }` in the tasks but is generally considered a bad practice and it is discouraged by the Gradle developers. See: https://www.stefan-oehme.com/stop-rerunning-tests

2) Set the severity level of style violations to `error` with `<property name="severity" value="error"/>` to the `checkstyle.xml`. This will make the Gradle tasks fail by reporting the style violations as errors.

3) Add `maxWarnings = 0` to the Gradle tasks to make them fail if a warning is reported. This is similar to the second solution because the tasks will again fail, but the style violations will still be marked as warnings instead of errors.

It should be decided if a style violation should result in a failed task or not. In my opinion, it would make sense for tasks that check the style of the code to fail, if there are any violations. However, it will also make it harder to do a build without fixing all style violations or disabling the failing, because the `build` task depends on the `checkstyle` tasks.

**Comment by DobromirM** [comment]
One additional drawback of not failing the task when a style violation occurs, is that if the top level `checkstyleTest` or `checkstyleMain` task is executed, the warnings are lost in all of the text and are hard to find.

For example, if there is a violation in the JSON module and the `checkstyle` task for the whole `swim-system` is executed, you would have to scroll manually trough the output for all different modules to find the warning.

**Comment by SirCipher** [comment]
I have updated the checkstyle standards in https://github.com/swimos/swim-system-java/commit/68bbff235eea38698084c7e6606294df6dea24a7 and I have added a CI pipeline for checkstyle. Any violations reported will cause that pipeline to fail. This will go live once the failing tests have been addressed.

**Comment by ajay-gov** [comment]
Great, thank for doing this.

**Comment by DobromirM** [comment]
The CI will detect the style issues, however the problem with the style issues being inconsistent locally is still present. I've disabled caching on the `checkstyle` Gradle tasks to ensure that the warnings are always reported. The same solution has already been used on the `test` tasks in Gradle.

See: #37
