### ISSUE TITLE
HTTP Routing Directives

### ISSUE THREAD

**Issue by c9r** [swimos/swim#5]
[`swim.web`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.web) contains a simple HTTP routing interface in [`WebRoute.java`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/WebRoute.java). The [`swim.web.route`](https://github.com/swimos/swim/tree/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/route) package contains various `WebRoute` implementations, such as [`PathPrefixRoute`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/route/PathPrefixRoute.java) and [`DirectoryRoute`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/route/DirectoryRoute.java).

A `WebRoute` takes a [`WebRequest`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/WebRequest.java) and returns a [`WebResponse`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/WebResponse.java). A `WebResponse` is a thin wrapper around a [`swim.io.http.HttpResponder`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.io.http/src/main/java/swim/io/http/HttpResponder.java). A [`WebRequest`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/WebRequest.java) wraps a `swim.http.HttpRequest`, and provides convenience methods for constructing `WebResponse`s. A `WebRequest` also contains a `routePath`, which is the `UriPath` against which path-selective `WebRoute`s should match. Path routes may consume and otherwise transform a `WebRequest`'s `routePath`.

So a _route_ is a function that transforms `WebRequest`s into `WebResponses`. A routing _directive_, on the other hand, refers to any function that returns other `WebRoute`s. The only real routing directive implemented at the moment is the [`WebRoute.orElse`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/WebRoute.java#L23) method, which returns instances of [`AlternativeRoute`](https://github.com/swimos/swim/blob/master/swim-system-java/swim-core-java/swim.web/src/main/java/swim/web/route/AlternativeRoute.java).

### Background

This approach to HTTP routing is inspired by Spray, which subsequently became Akka HTTP.  See Akka's [Routes](https://doc.akka.io/docs/akka-http/current/routing-dsl/routes.html) and [Directives](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/index.html) documentation, along with their list of [predefined directives](https://doc.akka.io/docs/akka-http/current/routing-dsl/directives/by-trait.html). We'd like `swim.web` to have similar routing capabilities to Akka HTTP, but with a focus on cleanliness and simplicity. Spray and Akka HTTP make elegant use of Scala implicits and higher kinded types to implement a concise routing DSL. We have neither implicits nor HKTs at our disposal, so we'll have to make due with higher order methods on the `WebRoute` interface, which should be just fine given our focus.

### Design

We will want to organize our routing directives into a set of `*Directive` interfaces, each containing default methods for a focussed set of routing tasks, which `WebRoute` will inherit. It's important that `WebRoute` remains a `@FunctionalInterface`, so `routeRequest` must remain `WebRoute`'s sole abstract method. In general, each directive will consist of a `WebRoute` subclass in the `swim.web.route` package that implements the routing logic, along with a combinator function in a `*Directive` interface which returns new instances of the `WebRoute` subclass parameterized by the arguments to the higher order directive function.

Route chaining should be achieved via higher order directive methods on `WebRoute` that take combinator functions as arguments. Combinator functions should generally take no arguments, unless the combinator extracts an element of the request, in which case the combinator should be a function with the extracted value as its argument. Combinator functions should return a `WebRoute`, to which the directive will delegate after evaluating the closure.

### Implementation

**Path Directives**
- [ ] Add `swim.web.route.PathDirectives` interface, extended by `WebRoute`.
- [x] Add a `pathPrefix` combinator function that takes a literal `UriPath`, and a constant `WebRoute` as its arguments, and returns an instance of `PathPrefixRoute`.
- [x] Implement `swim.web.route.PathPrefixDirective`, analogous to `PathPrefixRoute`, but which takes a `java.util.function.Supplier<WebRoute>` as its `then` argument, instead of a constant `WebRoute`.
- [x] Add a `pathPrefix` overload that takes a literal `UriPath`, and a `Supplier<WebRoute>`, as its arguments, and returns an instance of `PathPrefixDirective` (statically return typed as a `WebRoute`).
- [x] Implement `PathRoute` and `PathDirective`, analogous to `PathPrefixRoute` and `PathPrefixDirective`, that match the entire `routePath`, rather than its prefix.
- [x] Add `path` combinator methods to `PathDirectives`.
- [x] Add a `pathEnd` combinator method to `PathDirectives`, which should be shorthand for `path(UriPath.empty())`.

**Method Directives**
- [x] Add `swim.web.route.MethodDirectives` interface, extended by `WebRoute`.
- [x] Implement `MethodDirective`, parameterized by a `swim.http.HttpMethod` and `Supplier<WebRoute>`, which evaluates and delegates to its `then` closure if the `WebRequest`'s method equals the parameterized method.
- [x] Add a `method(HttpMethod, Supplier<WebRoute>)` combinator to `MethodDirectives`, along with `options`, `get`, `head`, `post`, `put`, `patch`, and `delete` convenience methods.

**Header Directives**
- [ ] Add `swim.web.route.HeaderDirectives` interface, extended by `WebRoute`.
- [ ] TBD: define header directives

**Host Directives**
- [ ] Add `swim.web.route.HostDirectives` interface, extended by `WebRoute`.
- [ ] TBD: define host directives

More advanced routing directives will be addressed in separate issues.

**Comment by ajay-gov** [comment]
Closing for now, will be addressed in swim5
